import React from 'react';
import { Link } from 'react-router-dom';
import {
    FileText,
    ShieldCheck,
    CheckCircle2,
    AlertCircle,
    Building2,
    Lock,
    Phone,
    Mail,
    Scale,
    Layers,
    Users,
} from 'lucide-react';
import LandingNav from '@/components/landing/LandingNav';
import LandingFooter from '@/components/landing/LandingFooter';
import './landing.css';

const RetailerTerms: React.FC = () => {
    return (
        <div className="landing-page relative overflow-x-clip bg-white text-slate-900 font-sans">
            <LandingNav />

            {/* HERO HEADER */}
            <section className="relative w-full border-b border-slate-100 bg-gradient-to-b from-[#f7fee7]/80 via-[#ecfccb]/30 to-white px-4 sm:px-6 py-14 sm:py-20">
                <div className="mx-auto max-w-4xl text-center">
                    <div className="inline-flex items-center gap-2 bg-[#f0fdf4] text-[#008c46] border border-[#bbf7d0] px-3.5 sm:px-4 py-1.5 rounded-full text-[0.7rem] sm:text-xs font-bold mb-4 shadow-2xs">
                        <FileText className="w-3.5 h-3.5 text-[#008c46]" />
                        <span>B2B Partner &amp; Merchant License Agreement</span>
                    </div>
                    <h1 className="text-3xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-[1.1]">
                        Shahparpay Retailer <span className="text-[#008c46]">Terms &amp; Conditions</span>
                    </h1>
                    <p className="mt-4 text-sm sm:text-lg text-slate-600 font-medium leading-relaxed max-w-3xl mx-auto">
                        Complete Master Agreement, License Rights, Wallet Balance Requirements, e-KYC Consent, Security Responsibilities, Service Activation Fee Schedule, and Termination Terms for Retailers and Distributors.
                    </p>
                </div>
            </section>

            {/* CONTENT BODY */}
            <section className="w-full bg-[#f8fafc] px-4 sm:px-6 py-14 sm:py-20 border-b border-slate-100">
                <div className="mx-auto max-w-5xl space-y-8">
                    {/* KEY SUMMARY CARDS */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div className="p-5 rounded-[24px] bg-white border border-slate-200 shadow-sm text-center">
                            <div className="w-10 h-10 rounded-xl bg-[#f0fdf4] text-[#008c46] flex items-center justify-center mx-auto mb-3">
                                <Users className="w-5 h-5" />
                            </div>
                            <h3 className="font-extrabold text-slate-900 text-sm">Eligibility Criteria</h3>
                            <p className="text-xs text-slate-500 mt-1">
                                Must be 18+ years of age, legally competent, and possess valid PAN, Aadhaar, and physical shop location proof.
                            </p>
                        </div>

                        <div className="p-5 rounded-[24px] bg-white border border-slate-200 shadow-sm text-center">
                            <div className="w-10 h-10 rounded-xl bg-[#f0fdf4] text-[#008c46] flex items-center justify-center mx-auto mb-3">
                                <Layers className="w-5 h-5" />
                            </div>
                            <h3 className="font-extrabold text-slate-900 text-sm">Wallet Trading Balance</h3>
                            <p className="text-xs text-slate-500 mt-1">
                                Retailers must maintain sufficient wallet trading balance through authorized Distributors or direct bank fund requests.
                            </p>
                        </div>

                        <div className="p-5 rounded-[24px] bg-white border border-slate-200 shadow-sm text-center">
                            <div className="w-10 h-10 rounded-xl bg-[#f0fdf4] text-[#008c46] flex items-center justify-center mx-auto mb-3">
                                <Scale className="w-5 h-5" />
                            </div>
                            <h3 className="font-extrabold text-slate-900 text-sm">60 Days Notice</h3>
                            <p className="text-xs text-slate-500 mt-1">
                                Agreement may be terminated by Retailer via 60 days written notice, or instantly by Company on misuse or fraud.
                            </p>
                        </div>
                    </div>

                    {/* ACTIVATION FEE BREAKDOWN TABLE */}
                    <div className="bg-white rounded-[28px] border border-slate-200 p-6 sm:p-10 shadow-sm space-y-6">
                        <div>
                            <h2 className="text-2xl font-extrabold text-slate-900 tracking-tight border-l-4 border-[#008c46] pl-3">
                                Product &amp; Service Activation Fee Schedule
                            </h2>
                            <p className="text-xs sm:text-sm text-slate-500 mt-1">
                                Standard pricing vs partner discounts for services available on the Shahparpay portal.
                            </p>
                        </div>

                        <div className="overflow-x-auto rounded-2xl border border-slate-200">
                            <table className="w-full text-left text-xs sm:text-sm">
                                <thead className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                                    <tr>
                                        <th className="p-3.5">Service Name</th>
                                        <th className="p-3.5">Standard Cost</th>
                                        <th className="p-3.5">Partner / Retailer Price</th>
                                        <th className="p-3.5">Status</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-100 text-slate-600">
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">PAN Card Services (NSDL)</td>
                                        <td className="p-3.5">₹500 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">AEPS Cash Withdrawal</td>
                                        <td className="p-3.5">₹500 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">Micro ATM Service</td>
                                        <td className="p-3.5">₹500 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">Domestic Money Transfer (DMT)</td>
                                        <td className="p-3.5">₹500 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">Digital Savings &amp; Current Account</td>
                                        <td className="p-3.5">₹1,000 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">BBPS &amp; Mobile / DTH Recharge</td>
                                        <td className="p-3.5">₹500 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">e-KYC Onboarding &amp; Bank Verify</td>
                                        <td className="p-3.5">₹50</td>
                                        <td className="p-3.5 font-bold text-slate-900">₹10 Only</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">Loan &amp; Credit Card Lead Gen</td>
                                        <td className="p-3.5">₹1,000 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-slate-900">ITR &amp; Tax Registration Suite</td>
                                        <td className="p-3.5">₹5,000 + GST</td>
                                        <td className="p-3.5 font-bold text-[#008c46]">FREE / Discounted</td>
                                        <td className="p-3.5">Live</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    {/* COMPLETE VERBATIM USER AGREEMENT DOCUMENT CARD */}
                    <div className="bg-white rounded-[28px] border border-slate-200 p-6 sm:p-10 shadow-sm space-y-6">
                        <div className="flex items-center justify-between border-b border-slate-100 pb-4">
                            <div className="flex items-center gap-2.5">
                                <FileText className="w-6 h-6 text-[#008c46]" />
                                <div>
                                    <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900">
                                        Complete Official User Agreement
                                    </h2>
                                    <p className="text-xs text-slate-500">
                                        Full text copy of Shahparpay Retailer Term and Condition (All Clauses &amp; Sections)
                                    </p>
                                </div>
                            </div>
                            <span className="text-xs font-extrabold px-3 py-1 rounded-full bg-[#f0fdf4] text-[#008c46] border border-[#bbf7d0]">
                                Complete Legal Record
                            </span>
                        </div>

                        <div className="space-y-4 max-h-[800px] overflow-y-auto pr-2 border border-slate-200 p-6 rounded-2xl bg-slate-50/70 text-slate-800">
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">USER AGREEMENT</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">IMPORTANT: THIS USER AGREEMENT (HEREINAFTER REFERRED TO AS “AGREEMENT”) IS A LEGAL AGREEMENT BETWEEN YOU (EITHER AN INDIVIDUAL OR, IF PURCHASED OR OTHERWISE ACQUIRED BY OR FOR AN ENTITY, AN ENTITY) (HEREINAFTER REFERRED TO AS “USER") AND SHAPARPAY SOLUTIONS PRIVATE.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">THIS AGREEMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THEREUNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORD/DOCUMENT IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS IS A COMPUTER-GENERATED ELECTRONIC RECORD AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURE.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">PLEASE READ THE TERMS AND CONDITIONS OF THIS AGREEMENT CAREFULLY BEFORE COMPLETING THE LOGIN, PROCESS AND USING THE WEBSITE AND/OR APPLICATIONS. THE USE OF THIS WEBSITE AND/OR APPLICATION AND THE CONTENT CONTAINED THEREIN IS GOVERNED BY THE FOLLOWING TERMS OF USE. WHEN YOU USE THIS PLATFORM, YOU ACKNOWLEDGE THAT YOU HAVE READ THE TERMS OF USE AND THAT YOU ACCEPT AND WILL BE BOUND BY THE TERMS AND CONDITIONS HEREOF. IF YOU DO NOT AGREE TO OR WISH TO BE BOUND BY THE TERMS OF USE, YOU MAY NOT ACCESS OR OTHERWISE USE THE WEB SITE. THESE TERMS MAY BE MODIFIED FROM TIME TO TIME WITHOUT NOTICE TO YOU BY POSTING REVISED TERMS ON OUR PLATFORM. IN ORDER TO USE THIS WEBSITE AND/OR APPLICATION, YOU MUST FIRST READ AND ACCEPT THE TERMS OF USE.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In order to use Website and/or applications, you must first read and accept the terms of this license.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">WHEREAS:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company is in the business of electronic transaction processing and online transactions of various services like Money Transfer, AEPS, Cash Withdrawal, Balance Inquiry, Mini Statement, Aadhaar Pay, AEPS Cash Deposit, Account Opening (IndusInd Bank), and Courier Services. (In future we are added recharge (mobile network, DTH, Digital Wallet Top ups), bill payments, cash management service (cash point), E-shopping, IRCTC) and other related business on real time basis through its network under B2B Model across the Republic of India (hereinafter referred to as ‘Services’) and owns a software which is a flexible and secure solution for payments, cash collections, validation and settlements (hereinafter referred to as ‘Software’).</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER is desired to offer the above-mentioned Services to the Customer from its locations situated within the Territory and desired to uses the Shahparpay Solutions Private Limited application which is operational on Desktops, Laptops and Mobile phones vide Android, Windows, iOS &amp; Java platforms.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company has developed its official website and/or application (Android and/or IOS) namely shahparpay.in and its subsites (hereinafter referred to as ‘Platform’) which has the features or offers to operate the business of Shahparpay Solutions Private Limited.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER has approached the Company and requested the Company to provide Service to the USER intending to purchase or inquiring for any products and/ or services of the Company by using Company's Platform or using any other customer interface channels of Company which includes its advertisements, information campaigns etc. to permit them to use of the Platform.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company has accepted the offer of USER and wishes to have a business relationship as subject to the following terms and conditions.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">USER and Company/ Shahparpay Solutions Private Limited shall jointly be referred to as “Parties” and individually as the “Party” as per the context.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">NOW THEREFORE IN CONSIDERATION OF THE PREMISE AND THE MUTUAL RIGHTS AND OBLIGATIONS HEREIN SET FORTH, THE PARTIES HERETO AGREE AS FOLLOWS:</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">DEFINITIONS:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Unless the contrary intention appears:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">“Applicable Laws” shall mean all laws of Republic of India, including ordinance, statutes, rules, orders, decrees, injunctions, licenses, permits, approvals, authorisations, consents, waivers, privileges, agreements and regulations of any governmental authority having jurisdiction over the relevant matter as such are in effect as of the Effective Date or as may be amended, modified, enacted or revoked from time to time in future;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Authorization" includes an authorization, consent, clearance, approval, permission, resolution, license, exemption, filing and registration;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">“Confidential Information” means any and all information in whatever form whether disclosed orally or in writing or whether eye readable, machine readable or in any other form including, without limitation, the form, materials and design of any relevant equipment or any part thereof, the methods of operation and the various applications thereof, processes, formulae, plans, strategies, data, know how, designs, photographs, drawings, specifications, technical literature and any other material made available by one Party to the other Party or gained by the visit by one Party to any establishment of the other Party whether before or after this Agreement is entered into, for the purpose of considering, advising in relation to or furthering the negotiations (and any information derived from such information).</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Content" means the text, documents, information, data, articles, images, photographs, graphics, software, applications, video recordings, audio recordings, sounds, designs, features, and other materials that are available on the Platform;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">“Customer” shall mean any person availing Services from the USER registered on the Platform;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">“Business Partner” shall mean the person/entity authorised by the Company to appoint the Marchant for the purposes of this Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">“Encumbrance” includes Any mortgage, charge (whether fixed or floating), pledge, equitable interest, lien, hypothecation, assignment, deed of trust, title retention, security interest, encumbrance of any kind securing or conferring any priority of payment in respect of any obligation of any Person, including any right granted by a transaction which, in legal terms is not the granting of security but which has an economic or financial effect similar to the granting of security under Applicable Law;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Any proxy, power of attorney, voting trust, contract, interest, option, right of other Persons, right of set off, right of first offer, refusal or transfer restriction in favour of any Person;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Any adverse claim as to title, possession or use, conditional sale contract, co-sale contract, trust (or other title exception of whatsoever nature);</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Other commitment, restriction, limitation or encumbrance of any kind or nature whatsoever including restriction on use, voting rights, transfer, receipt of income or exercise of any other attribute of ownership; and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">A contract, whether conditional or otherwise, to give or refrain from giving any of the foregoing.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">“Intellectual Property Rights” means, without limitation, Content, Software, trademarks, service marks, trade names, word marks, registered and unregistered design rights, copyrights (including rights in computer software), database rights and all other similar rights, title and interest which may subsist in any part of the world now or in the future (including know-how constituting a trade secret) under any statute or under common law and where such rights are obtained or enhanced by registration together with any extensions or renewals, any registration of such rights and applications and rights to apply for such registrations;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Member" means an individual who has registered with the Platform and have created a Member ID and a password on the Platform;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Member ID" means the unique IDUSER uses (with password) to login to the Platform;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Person" includes an individual, statutory corporation, body corporate, partnership, joint venture, association of persons, Hindu Undivided Family (HUF), societies (including co-operative societies), trust, unincorporated organization, government (central, state or otherwise), sovereign state, or any agency, department, authority or political subdivision thereof, international organization, agency or authority (in each case, whether or not having separate legal personality) and shall include their respective successors and assigns and in case of an individual shall include his legal representatives, administrators, executors and heirs and in case of a trust shall include the trustee or the trustees for the time being;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Platform" means the shahparpay.in website and/or applications, and their respective subsites, computer or mobile running applications (Android and/or IOS) together with the respective Content, Intellectual Property Rights of Shahparpay Solutions Private Limited, Products and Services available from these sites/ subsites or applications;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Products and Services" means the services and products offered by the Shahparpay Solutions Private Limited (as specified in Recital A) under B2B model through the Platform;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Provider" means the ultimate suppliers, information providers, and other service providers whose product/services are being offered by the Shahparpay Solutions Private Limited;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Purchase" means to book, reserve, or purchase. The terms "Platform", "Intellectual Property Rights", "Content" and "Products and Services" do not include the sites, marks, content, products or services that are provided by third parties, and that are available through a link from the Platform. Their use is subject to the terms set forth by their respective owners or operations, on the third party's website and/or application;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Territory" shall mean the territory as selected by the User while registering on the Company's Platform;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono bg-slate-50 p-2.5 rounded-lg border border-slate-200">"Trading Balance" shall mean the amount to be deposited by User in advance with the Company's bank account as designated by the Company from time to time for the purpose of day-to-day trade and fulfilling its obligations as specified herein under this Agreement.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">INTERPRETATION</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The words “include” or “including” shall be construed without limitation;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">a gender shall include references to the female, male and neuter genders;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">a "month" is a reference to a period starting on one day in a calendar month and ending on the date immediately before the numerically corresponding day in the next calendar month, except that if there is no numerically corresponding day in the month in which that period ends, that period shall end on the last day in that calendar month;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The singular includes the plural (and vice versa);</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">SCOPE OF THE AGREEMENT:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company agrees to permit the User to register its details in the Company’s Platform. The USER shall choose a password and shall be solely responsible to maintain the confidentiality of its password and account. The USER is fully responsible for all activities that occur while using their password or account. It is the duty of the USER to notify the Company immediately of any unauthorized use of their password or account or any other breach of security. The Company shall not be liable for any loss that may be incurred by the USER as a result of unauthorized use of their password or account, either with or without their knowledge.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Additionally, the Company itself may provide terms and guidelines that govern particular features, offers or the operating rules and policies applicable to each Product or Service of the Company. The User shall be responsible for ensuring compliance with the terms and guidelines or operating rules and policies of the Provider with whom the USER elects to deal, including terms and conditions set forth in a Providers' fare rules, contract of carriage or other rules.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees that they shall not distribute exchange, modify, sell or transmit anything from the Company’s Platform, including but not limited to any text, images, audio and video, for any business, commercial or public purpose.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company reserves the right, in its sole discretion, to terminate the access to any or all Company’s Platform or its other sales channels and the related services or any portion thereof at any time, without notice, for general maintenance or any reason what so ever.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It is agreed between the Parties that, as long as the USER comply with the terms of this Agreement, the Company agrees to provide a non–exclusive, non–transferable, limited right to enter, view and use its Platform to the USER. The USER agrees not to interrupt or attempt to interrupt the operation of the Platform in any manner.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Access to certain areas of the Company’s Platform may only be available to registered Members. To become a registered Member, the USER shall be required to answer certain questions at the request of the Company. Answers to such questions may be mandatory and/or optional. The USER represents and warrants that all information provided to the Company whether while answering such questions or otherwise are true and accurate.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Some or all Products and Services displayed on the Platform may not be available for purchase in particular country or locality of the USER. The reference to such products and services on the Platform does not imply or warrant that these products or services shall be available at any time in particular geographical location. The USER shall check with Company’s local authorized representative for the availability of specific Products and Services in the USER area.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In addition to this Agreement, there are certain terms of service specific to the Services rendered/ products provided by the Company, such terms of service shall be provided/ updated by the Company from time to time which shall be deemed to be a part of this Agreement and in the event of a conflict between such terms of service and this Agreement, the terms of this Agreement shall prevail.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company’s Services are offered to the USER subject to its acceptance without modification of all the terms, conditions and notices contained in this Agreement and the terms of service, as may be applicable from time to time. For the removal of doubts, it is clarified that availing of the Services by the User constitutes an acknowledgement and acceptance by the USER of this Agreement and the terms of service. If the USER does not agree with any part of such terms, conditions and notices, the User must not avail the Company’s Services.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">TERMS OF ELIGIBILITYFOR PLATFORM USER(S):</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">USERS mean any person who uses and has the right to use the Services provided by Shahparpay Solutions Private Limited on the Platform.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Services are available to those persons who can form legally binding contracts under the Applicable Laws. Therefore, USER should not be a minor or otherwise incompetent as per Applicable Laws; i.e. USER must have completed the age of 18 years of age to be eligible to use Services.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">USER shall; while accessing the Platform, they must follow/abide by the Applicable Laws. Shahparpay Solutions Private Limited is not responsible for the possible consequences caused by your act/behaviour during the use of Platform. Shahparpay Solutions Private Limited may, in its sole discretion, refuse the Service to anyone at any time without assigning any reason.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">TERM AND TERMINATION:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">This Agreement shall take effect and become binding upon the Parties immediately after the User has signed up and created an account on the Platform and remain in force until it is terminated by either of the Parties in accordance with the terms of the Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">This Agreement may be terminated by Company immediately without any reason thereof, if the USER misuses the Platform or fails to comply with the terms and conditions of this Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">This Agreement may be terminated by USER by serving 60 days written notice in advance by his/her registered mobile number and/or email id either to the Company or through Distributor to the Company, if applicable.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Upon termination of this Agreement for whatever reason, all the rights and obligations of the Parties hereunder shall cease.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">USER’S RESPONSIBILITY OF CONGNIZANCE OF THIS AGREEMENT:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees that if the USER downloads any Content from Platform, the USER will not remove any Intellectual Property notices or other notices that go with it.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company agrees to make every effort to ensure that the description and content on each page of the Platform is correct, it does not, however, take responsibility for changes that may occur due to human/ data entry errors or for any loss or damages suffered by any USER due to any information contained therein. Also, the Company does not own or operate the services of service Provider and cannot therefore control or prevent changes in the published descriptions. The Company reserves the right to make changes therein from time to time.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall ensure that sufficient Trading Balance is maintained by the USER and the same can be taken/maintained through their, authorized Distributor or Sub-Distributor or Business Partner or directly from Shahparpay Solutions Private Limited.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER should not take any action based on information on the Platform until it receives a confirmation of such transaction. If the USER does not receive a confirmation of the purchase on Platform via e-mail or SMS, (check in "spam" or "junk" folder to verify that it has not been misdirected), and if still not found, USER shall contact customer service department of the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company agrees to take all measures to exclude viruses from the Platform but does not ensure that the Platform will be at all times free from viruses or other destructive software(S). The USER shall take appropriate safeguards before downloading information from the Platform. The Company shall not be responsible for any loss/damages to computer equipment or other property resulting from the use of the Platform or due to any downloads from the Platform.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees and acknowledges that the Company’s Platform may contain links to other website and/or applications. The said other website and/or applications are not under the control of the Company and hence, the Company is not responsible for the content of any other website and/or applications, or any changes and updates to other website and/or applications. The Company is providing these links toother website and/or applications to the USER only as a convenience, and their inclusion does not entail endorsement by the Company of the other website and/or applications or any association with its operators or owners.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees and acknowledges that on accepting the terms and conditions of this Agreement, the User gives the right to the Company to collect the data relating tohis/her/its location (at a GPS level), browser details, capturing photograph (for the purposes of the Agreement only) and any other details as Company may require from time to time for the purposes of this Agreement. The USER also allows Company to send SMS, email and/or messages on WhatsApp messenger to the Marchant in relation to the services at the registered mobile number and email address as provided by the USER while registration on the Platform in accordance with Applicable Laws including but not limited to Information Technology Act, 2000.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company acts only as a business agent and accepts no liability whatsoever for any part of the arrangements between the Provider and the Customer with regard to the standard of service. In no circumstances the Company shall be liable for the services provided by the Provider/third party.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">If the Platform contains bulletin boards, chat rooms, access to mailing lists or other message or communication facilities, the USER agrees to use the same only to send and receive messages and materials that are proper and related thereto. The USER agrees that when using the Platform or any facility available there from, shall not do any of the following:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Publish, post, distribute or disseminate any defamatory, infringing, obscene, indecent or unlawful material or information.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Upload or attach files that contain software or other material protected by Intellectual Property laws (or by rights of privacy and publicity) unless the USER owns or controls the rights thereto or has received all consents therefor as may be required by Applicable Law.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Upload or attach files that contain viruses, corrupted files or any other similar software or programs that may damage the operation of another’s computer.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Delete any author attributions, legal notices or proprietary designations or labels in any file that is uploaded.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Falsify the origin or source of software or other material contained in a file that is uploaded.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Advertise or offer to sell any goods or services, or conduct or forward surveys, contests or chain letters, or download any file posted by another user of a forum that the USER knows, or reasonably should know, cannot be legally distributed in such manner.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees that, it shall not post or transmit any defamatory, libellous, obscene, pornographic, profane, threatening or unlawful material or any material that could constitute or encourage conduct that would be considered a criminal offense or give rise to civil liability, or otherwise violate any Applicable Laws. The Company assumes no liability or responsibility arising from the contents of any communications containing any defamatory, erroneous, inaccurate, libellous, obscene or profane material. The Company may change, edit, or remove any user material or conversations that are illegal, indecent, obscene or offensive, or that violates the Company’s policies in any manner way.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company agrees to fully cooperate with any law enforcement authorities or court order requesting or directing the Company to disclose the identity of anyone posting such materials.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Any communications or materials send by the USER to the Platform by electronic mail or otherwise, including any comments, data, questions, suggestions or the like, all such communications are, and will be treated by the Company, as non–confidential. The USER hereby gives up any and all claim that any use of such material violates any of rights including moral rights, privacy rights, proprietary or other property rights, publicity rights, rights to credit for material or ideas, or any other right, including the right to approve the way the Company uses such material. Further, any material submitted to this Platform may be adapted, broadcast, changed, copied, disclosed, licensed, performed, posted, published, sold, transmitted or used by the Company.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">REPRESENTATION AND WARRANTIES</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER represents and warrants to the Company that:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It will submit all the details as requested by the Company including but not limited to KYC information along with proof of the location of office/shop in a true, correct &amp; accurate manner and shall not make any false and/or misleading representation in relation to the same. User understands that any false and/or misrepresentation including submission of false documents can lead to suspension/termination of the registration on the Platform and the USER shall be liable to bear all/any legal consequences arising thereto;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It validly exists and in good standing under the Applicable Laws and it has the power and authority to enter into and fully perform the obligations under this Agreement;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It has all requisite power and authority to execute, deliver and perform its obligations under this Agreement and has been fully authorized by all requisite corporate actions to do so;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It has the necessary skills, knowledge, experience, equipment’s, resources, expertise, the required capital, net worth, adequate and capability to duly perform its obligations in accordance with the terms of this Agreement and to the satisfaction of Shahparpay Solutions Private Limited;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">There are no criminal complaints or other proceedings pending against the USER with the police, courts or other authorities which may hamper in fulfilling its obligations under this Agreement;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It has obtained and will maintain all necessary approvals, permits, waivers, consents and licenses from the relevant authorities for it to perform all its obligations under this Agreement;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It shall not use the Services for any improper or unlawful purposes;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It will not knowingly make any false or misleading representation with regard to the Services to the Merchant;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It shall not undertake any activity while providing services which is infringing any third-party rights including third party Intellectual Property Rights;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The execution and performance of this Agreement by the USER does not and shall not violate any provision of any existing arrangement, law, rule, regulation, any order or judicial pronouncement;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It will comply with the provisions of all the Applicable Laws, concerning or in relation to rendering of Services by the USER as envisaged under this Agreement;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It shall be solely liable and responsible for compliance of Applicable Laws in respect of its employees, agents and representatives and including laws relating to terminal benefits such as pension, gratuity, provident fund, bonus or other benefits to which its employees, agents and representatives may be entitled and the Company shall have no liability in this regard.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">OWNERSHIP:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">It is agreed between the Parties that, all materials on Platform, including but not limited to audio, images, software, text, icons and such like (the “Content”), belongs to the Shahparpay Solutions Private Limited. The USER shall not use the Content, except as specified therein. The USER agrees to follow all instructions on Platform limiting the way USER may use the Content. The Platform is the sole and exclusive property of the Company or its licensors. The Company and its licensors retain all right, title and interest (including all copyright, trademark, patent, trade secrets, and all other Intellectual Property Rights) in the Platform. Any unauthorized use, reproduction or modification of the Platform may violate the Applicable Laws.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">There are a number of Intellectual Property Laws including but not limited to proprietary logos, service marks and trademarks found on Platform whether owned/used by the Company or otherwise. By displaying them on the website and/or application, the Company is not granting the USER any license to utilize those Intellectual Property Laws, proprietary logos, service marks, or trademarks. Any unauthorized use of the Content may violate the laws of privacy and publicity.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">FEES PAYMENT&amp; TAXES:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company reserves the right to charge transaction fees from the USER based on certain completed transactions using the Services.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">All the applicable charges (as decided by PDSPL from time to time) along with the applicable taxes on the said charges for the usage of Merchant Panel and its associated application shall be deducted by PDSPL from the Trading Balance of the Merchant on monthly basis against which PDSPL shall raise an invoice for amount payable by the Merchant by the end of the next month.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company further reserves the right to alter any and all type of fees/renewal charges/usage charges etc from time to time, without notice. The USER shall be completely responsible for all charges, fees, duties, taxes, and assessments arising out of the use of the Services.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In the rare possibilities of the transaction not initiated or confirmed, the Company shall not be under any obligation to make another transaction in lieu of or to compensate/ replace the unconfirmed one. All subsequent further transactions will be treated as new transactions with no reference to the earlier unconfirmed reservation.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The User understands and acknowledges that the Company will settle the Payments to Provider Account only upon actual receipt of the Payments in the Bank Account of the company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall be liable for all applicable taxes including not limited to GST with respect to the Services rendered. Any applicable indirect taxes under Applicable Laws on supply of Services shall be in addition and USER shall be liable for the same.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In case USER fails to pay any applicable taxes or liabilities required under Applicable Laws, statutory and government regulations and accordingly if Company is made liable to pay the same; by virtue of such arrangement, the USER acknowledges that Company shall have the right to adjust such amount against the subsequent net payables.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall be required to indemnify and hold harmless the Company, its promoters, officers, directors, employees, affiliates, agents, sub-contractors and other representatives from any losses including loss of input tax credit, claims, demands, liabilities, suits, proceedings, penalties, costs or expenses of any kind (including, attorneys fees and expenses) on account of violation of applicable tax laws by the User (including but not limited to non-filing of the requisite forms with the tax authorities to claim tax credit, incorrect SAC codes, incorrect tax rates etc.).</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall fully indemnify the Company for any claim, liability, damages and costs arising out of any non-compliance of applicable GST and other applicable taxation laws.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">DATA PROTECTION</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">For the purpose of this Agreement, data protection legislation means the legislation and regulations relating to the protection of personal data of the Customers and Company and processing, storage, usage, collection and/or application of personal data or privacy of an individual under the Applicable Laws including (without limitation):</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">the Information Technology Act, 2000 (as amended from time to time), including the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 (Privacy Rules) and any other applicable rules framed thereunder;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">all other banking industry guidelines (whether statutory or non-statutory) or codes of conduct relating to the protection of personal data and processing, storage, usage, collection and/or application of personal data or privacy of an individual issued by any regulator to the Company; and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">any other Applicable Law solely relating to the protection of personal data and processing, storage, usage, collection and/or application of personal data or privacy of an individual.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER and its affiliates shall comply with all data protection laws under the Applicable Laws and such compliance shall include, but not be limited to, maintaining a valid and up to date registration or notification (where applicable) under the data protection laws.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall only undertake the processing of personal data: -</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">reasonably required in connection with the performance of its obligations under this Agreement; and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">in accordance with Company’s written instructions, and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">in accordance with Applicable Law.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Company hereby instructs the USER to take such steps in the processing of personal data on behalf of Company as are reasonably necessary for performance of its obligations under this Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall not process or transfer any personal data outside India without the prior written consent of Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall at all times have appropriate technical and organisational measures in place acceptable to Company:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">to prevent unauthorised or unlawful processing of any personal data of the Customers;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">to protect any personal data against accidental loss, destruction or damage;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">to ensure the reliability of its employees/contractor having access to the personal data;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">On Company’s request, the USER shall provide a detailed, written description of the measures undertaken by the USER and the USER’s compliance with those measures; and allow Company to access USER’s premises to inspect its procedures for the processing of personal data;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">If the USER receives a request from any person for access to personal data or any other request relating to Company’s obligations under the data protection laws, or any complaint or allegation that Company is not complying with the data protection laws the USER shall:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">immediately notify Company; and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">provide full co-operation and assistance to the Company in relation to any such complaint or request including, without limitation;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">providing Company with full details of any such request;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">providing Company with any personal data it holds in relation to any person in a form specified by Company within ten (10) days of receipt of the request from any person or as otherwise stipulated by Company and comply with the data access request within the relevant timescales set out in the data protection legislation and in accordance with explicit Authorisation to do so from Company;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">assist the Company in taking any action that deems appropriate to deal with such complaint or allegation;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER understands that in case the USER shares any personal information (including biometrics) and/or any information relating to its account on Shahparpay Solutions Private Limited with any third party (any person other than authorised personnel of the Company) or shares any OTP (One Time Password) with any third party, the USER shall be solely responsible for any losses/damages that it may incur from the same. The Company shall not be responsible for any such losses/damages incurred by the USER due to any unauthorised access to the account of the USER registered on the Platform.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall not sub-contract to any third party any of its obligations to process personal data on behalf of Company unless all of the following provisions of this Clause have first been complied with: -</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER has provided Company with such information and Company may require to ascertain that such sub-contractor has the ability to comply with the provisions of this Agreement; and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER has obtained the prior written consent of Company; and</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">the proposed sub-contractor has entered into a contract with Company on the same terms and conditions contained herein;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Upon expiry or termination of this Agreement for any reason the USER shall immediately return any personal data, destroy any personal data held by it or its affiliates or subcontractors and issue a confirmation of compliance in this regard to Company.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">SUB-CONTRACTING AND ASSIGNMENT</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER shall itself perform its obligations under this Agreement and shall not assign, transfer or sub-contract any of its rights and obligations in relation to all or part of the Service or related thereto, under this Agreement, except with the prior written permission of the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In the event of sub-contracting, the USER shall at all times remain responsible and liable to Company for all the actions of the sub-agents/ sub-contractors, assignee, or transferee, as the case may be, with no dilution or diminution of Service, controls, penalties, etc.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Notwithstanding anything contained in the terms of this Agreement, the USER shall ensure that such sub-agent, sub-contractor, assignee or transferee, as the case may be, under the provisions of this clause as agreed under this Agreement, are bound by the terms of this Agreement</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">If such assignment is as a result of operation of any Applicable Laws, then the Company shall have the option on such assignment to forthwith terminate this Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company shall be entitled to assign/transfer part / all of its rights and benefits under this Agreement to any person or entity with intimation or notice to the USER.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">AUDIT AND INSPECTION</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The CP hereby agrees and acknowledges that-</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company shall be entitled to access the USER’s records of transactions and other necessary information given to, stored or processed by the User relating to the Services rendered under this Agreement;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Following a reasonable notice period of 2 days, Company/Service Provider shall be entitled to conduct audits/inspection by its internal or external auditors, or by agents appointed to act on its behalf and to obtain copies of any audit or review reports and findings made on the USER in connections with the Services undertaken for / on behalf of Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Statutory body/Government Authority or any other competent authority or persons authorised by it shall be entitled to access the documents, records of transactions, and other necessary information given to, stored or processed by the USER within a reasonable time.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Statutory body/Government Authority shall be entitled to cause an inspection to be made on the USER and its books and account by one or more of its officers or employees or other persons.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">USAGE OF MOBILE NUMBER OF THE USER BY THE COMPANY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company agrees to send transaction confirmation &amp; other information to update the USER on the transaction status and any further information via SMS (short messaging service) and/or Whatsapp messages on the mobile number provided by the USER at the time of purchase of Product or Services. The USER hereby unconditionally consents such intimation via SMS/Whatsapp messages by the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">However, if the USER, does not want to receive mailers, SMS/Whatsapp messages/E-mail, can unsubscribe (opt out), For unsubscribing user can either email the Company at shahparpay@gmail.com, by providing USE</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">R details and other information as requested (for e.g. username, registered email &amp; SMS) or by using such other mode to unsubscribe as communicated by the Company to USER from time to time. USER can be rest assured their email id &amp; mobile number will not be shared with third party and will be exclusively kept confidential for internal use.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">CONTESTS AND INTERACTIONS:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Parties agree that Platform may contain certain contests which may require the USER to send Company some material and/or information about the USER or offer prizes. Each contest shall contain its own rules, which USER shall be required to read and accept before participating in the same.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">RIGHT TO CANCELLATION BY THE COMPANY IN CASE OF INVALID INFORMATION FROM THE USER:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER expressly undertakes to provide to the Company only correct and valid information while requesting for any Services under this Agreement, and not to make any misrepresentation of facts at all. Any default on part of the User would vitiate this Agreement and shall disentitle the USER from availing the Services from the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In case if the Company discovers or has reasons to believe at any time during or after receiving a request for Services from the USER that the request for Services is either unauthorized or the information provided by the USER or any of them is not correct or that any fact has been misrepresented by them, the Company in its sole discretion shall have the unrestricted right to take any steps against the USER, including cancellation of the transactions, etc. without any prior intimation to the USER. In such an event, the Company shall not be responsible or liable for any loss or damage that may be caused to the USER or any of them as a consequence of such cancellation of transaction or Services.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER unequivocally indemnifies the Company of any such claim or liability and shall not hold the Company responsible for any loss or damage arising out of measures taken by Company for safeguarding its own interest and that of its genuine customers. This would also include Company denying/cancelling any transaction on account of suspected fraud transactions.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">PRIVACY AND SECURITY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The User hereby consents, expresses and agrees that they have read and fully understands the Privacy Policy of the Company contained in the Company’s Platform and hereby consents that the terms and contents of such Privacy Policy are acceptable to them.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">DISCLAIMER OF WARRANTY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company and its Providers make no warranty of any kind regarding the Platform, Content, Products or Services, all of which are provided on an "as is" basis. The Company and its Providers expressly disclaim any representation or warranty that the Platform will be free from errors, viruses or other harmful components, that communications to or from the Platform will be secure and not intercepted and that the Services and other capabilities offered from/on the Platform will be uninterrupted, or that its Content will be accurate, complete or timely. The fact that the Company is including or offering any Product or Service on the Platform is not an endorsement or a recommendation of the Product or Service.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Other than those warranties which, under the Applicable Laws are applicable to these terms, are implied by laws, and are incapable of exclusion, restriction or modification, the Company and its providers expressly disclaim all warranties and conditions, including implied warranties and conditions of merchantability, fitness for a particular purpose, title, non-infringement, and those arising by statute or otherwise in Applicable laws or from a course of dealing or usage of trade.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">LIMITATION OF LIABILITY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Subject to Applicable Law, use of the Platform and its Content is at USER’s own risk. Services and Products made available on the Platform are subject to conditions imposed by the Providers, including but not limited to tariffs, conditions of carriage, international conventions and arrangements, and federal government regulations. Providers who furnish products or Services through the Platform are independent contractors, and not agents or employees of the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In no event the Company or its Providers shall be liable to any USER for any direct, indirect, special or other consequential damages for any use of the Platform, any hyper linked website, the acts or omissions of providers who furnish products or Services through the Platform, or the Products or Services offered by Providers through the Platform, including, without limitation, whether based in contract, tort, negligence, strict liability or otherwise, that arises out of or is in any way connected with(i) any use of, browsing or downloading of any part of Platform or Content, (ii) any failure or delay (including without limitation the use of or inability to use any component of the Platform for transaction), or (iii) the performance or non-performance by Shahparpay Solutions Private Limited or any Provider, or (iv) any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, even if the Company and the Provider(s) have been advised of the possibility of damages to such parties or any other party.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">User hereby acknowledge that the Company is not the seller of the Products and the Services and the Company shall in no manner be deemed to be the seller of the Products or Services, Company is only facilitating purchase of the Products or Services from the service Provider/vendor by providing the Services Platform of the Company. Hence, if there is any defect/deficiency in the Product Services of any nature whatsoever, then the Company may advise the User to contact the respective Provider and if there is any loss, cost, damage and liability which may incur or arise on the USER due to termination of relation/arrangement between the Company and the service Provider on account of any reason whatsoever than the Company shall not be held responsible, in any manner, to refund any amount in full or in part which has been paid by the USER while subscribing to the service of such service Provider at Company’s Platform.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">CONFIDENTIALITY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Each of the Party recognizes, accepts and agrees that all information obtained or disclosed, including but not limited to all data, documents, applications, papers, statements, slips, programmes, plans and/or any business/ customer information, marketing strategies/plans and any and all other trade secrets, confidential knowledge or information of either Party relating to its business, practices and procedures (hereinafter collectively referred to as “Confidential Information”) which may be provided or communicated by one Party to the other Party in connection with this Agreement and/or in the course of performance under this Agreement, shall be and shall remain the sole property of the Party providing such Confidential Information and shall be of a strictly private and confidential in nature and shall be treated as confidential by the other Party.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">During the Term of this Agreement and thereafter, neither Party shall make use of any such Confidential Information for any purpose whatsoever which is not necessary for the discharge of its obligations under this Agreement, or to the disadvantage of the Party providing such Confidential Information, nor shall the Party receiving such Confidential Information divulge it to anyone other than the Party providing the Confidential Information or persons designated by such Party.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">All Confidential Information shall be returned forthwith by the Party receiving such Confidential Information to the Party providing the Confidential Information upon the expiry or termination of this Agreement:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The obligations of each of the Party contained in this Clause shall continue for the Term of this Agreement and five (5) years after the termination of this Agreement but shall not apply to any information which: (a) is or hereafter comes into the public domain otherwise than through a breach by any Party of its obligations under this Agreement; (b) is, at the time of disclosure, already known to the Party receiving the Information as evidenced by such Party’s written documentation; (c) is independently developed by employees of the Party receiving the information who have not had access to or received any such Information under this Agreement; or (d) is required to be disclosed for the purpose of providing assistance hereunder subject to the other Party’s prior consent to the same: Provided, however, that nothing contained in this Clause shall prevent any Party from disclosing such Confidential Information to the extent required in or in connection with legal proceedings arising out of this Agreement or any matter relating to or in connection therewith.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Neither Party shall issue any public statement concerning these arrangements or disclose the contents hereof or matters related thereto to the public or any third party except with the express prior written approval of the other Party or except as required under Applicable Law.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The provisions of this Clause shall survive the termination or expiry of this Agreement.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">INTELELCTUAL PROPERTY RIGHTS</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">All Intellectual Property Rights of the Company in the Platform and the publicity material shall remain the property of the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Except as expressly set out in this Agreement no assignment of or license under any Intellectual Property Right or trade mark or service mark, whether registered or not, owned or controlled by the Company is granted to the USER by this Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">USER shall not use the Intellectual Property Rights or adopt any Intellectual Property Rights identical or similar to any of the Intellectual Property Right of the Company on or in relation to any Products or Services unless authorized by Company in writing. If the USER comes to know of any instances of misuse of any of the Intellectual Property Right of Company by third parties in its Territory, it shall forthwith notify Company and render all reasonable assistance to the Company in any proceedings that Company may take to prevent such misuses.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">During the Term of this Agreement and thereafter, the USER recognizes that Company is the sole owner of all Intellectual Property Rights, tile in the Services offered by Company including the technology and Software related thereto and all advertising and promotional material and Customer information related to provision of Services, and the goodwill which is or which shall become attached to any of the foregoing (hereinafter collectively known as “Company Intellectual Property"). The USER hereby knowledges that it shall have no right, title or interest, whatsoever in the Company Intellectual Property except expressly provided herein.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees, warrants and undertakes that it shall take all necessary measures to ensure that the Company Intellectual Property, Intellectual Property Rights of the service Providers are not infringed, passed off, diluted, reverse-engineered, hacked into misappropriated, tampered with and/or copied for any other reason by any of its employees, agents, consultants, representatives except expressly provided herein.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">RIGHT TO REFUSE:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Without prejudice to the other remedies available to the Company under this Agreement, the terms of Service or under Applicable Law, the Company may limit the USER’s activity, or end the USER's listing, warn other users of the USER's actions, immediately temporarily/indefinitely suspend or terminate the USER's registration, and/or refuse to provide the USER with access to the Platform if:</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER is in breach of this agreement, the terms of Service and/or the documents it incorporates by reference;</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company is unable to verify or authenticate any information provided by the USER; or</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company believes that the USER's actions may infringe on any third-party rights or breach any Applicable Law or otherwise result in any liability for the USER, other users of the Platform and/or the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company may at any time in its sole discretion reinstate suspended USER. Once the USER has been indefinitely suspended the USER shall not register or attempt to register with the Company or use the Platform in any manner whatsoever until such time that the USER is reinstated by the Company.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Notwithstanding the foregoing, if the USER breaches this Agreement, the Terms of Service or the documents it incorporates by reference, the Company reserves the right to recover any amounts due and owing by the USER to the Company and/or the service Provider and to take strict legal action as the Company deems necessary.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">FORCE MAJURE:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees that there can be exceptional circumstances where the service Providers may be unable to honour the confirmed bookings/purchases made by a USER on the Platform due to various reasons like climatic conditions, labour unrest, insolvency, business exigencies, government decisions, operational and technical issues, route and flight cancellations etc. If the Company is informed in advance of such situations where dishonour of bookings may happen, it will make its best efforts to provide similar alternative to its customer’s or refund the booking amount after reasonable service charges, if supported and refunded by that respective service Providers. The USER agrees that the Company being an agent for facilitating the booking services shall not be responsible for any such circumstances and the Customers have to contact that service Provider directly for any further resolutions and refunds.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees that in situations due to any technical or other failure in the Company, Services committed earlier may not be provided or may involve substantial modification. In such cases, the Company shall refund the entire amount received from the Customer for availing such Services minus the applicable cancellation, refund or other charges, which shall completely discharge any and all liabilities of the Company against such non-provision of Services or deficiencies. Additional liabilities, if any, shall be borne by the USER.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company shall not be liable for delays or inabilities in performance or non-performance in whole or in part of its obligations due to any causes that are not due to its acts or omissions and are beyond its reasonable control, such as acts of God, epidemic, pandemic (including Covid-19) fire, strikes, embargo, acts of government, acts of terrorism or other similar causes, problems at airlines, rails, buses, hotels or transporters end. In such event, the user affected will be promptly given notice as the situation permits.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Without prejudice to whatever is stated above, the maximum liability on part of the Company arising under any circumstances, in respect of any Services offered on the site, shall be limited to the refund of total amount received from the Customer for availing the Services less any cancellation, refund or others charges, as may be applicable. In no case the liability shall include any loss, damage or additional expense whatsoever beyond the amount charged by the Company for its Services.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">In no event shall the Company and/or its Providers be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the Company’s Platform or any other channel. Neither shall Company be responsible for the delay or inability to use the Company Platform or related services, the provision of or failure to provide Services, or for any information, Software, products, services and related graphics obtained through the Company website and/or application(s), or otherwise arising out of the use of the Company website and/or application(s), whether based on contract, tort, negligence, strict liability or otherwise.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company is not responsible for any errors, omissions or representations on any of its pages or on any links or on any of the third-party website and/or application pages.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">INDEMNIFICATION:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER agrees to indemnify, defend and hold harmless the Company and/or its affiliates, their Platform and their respective lawful successors and assigns from and against any and all losses, liabilities, claims, damages, costs and expenses (including reasonable legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by the Company and/or its affiliates, partner Platform and their respective lawful successors and assigns that arise out of, result from, or may be payable by virtue of, any fraud or breach, or non-performance of any representation, warranty, covenant or Agreement made or obligation to be performed by the USER pursuant to this Agreement. The USER shall be solely and exclusively liable for any breach of any country specific rules and regulations or general code of conduct and Company cannot be held responsible for the same</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">RELATIONSHIP:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">None of the provisions of any Agreement, terms and conditions, notices, or the right to use the Platform by the User contained herein or any other section or pages of the Company Platform or its partner website and/or applications, shall be deemed to constitute a partnership between the USER and the Company and no Party shall have any authority to bind or shall be deemed to be the agent of the other in any way</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">NOTICE:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">All notices, requests, consents, approvals, agreements, authorizations, acknowledgements, waivers and other communications required or permitted hereunder shall be in writing and in the English language and shall be sent by either internationally recognized courier or by email address or facsimile transmission (with confirming facsimile receipt) addressed to the address of each Party set forth below, or to such other address as such other Party shall have communicated to the other Party in writing. Notice shall be deemed to have been served when received (and in case of a facsimile transmission, provided that a confirming copy is sent to the other Party, in accordance with the non-facsimile notice delivery requirements).</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Shahparpay Solutions Private Limited:Address: 4/1 Victoria Lane, Telinipara, Bhadreswar, Hooghly, West Bengal - 712125E-mail: - shahparpay@gmail.com, Office Phone +91 8240039776</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">SEVERABILITY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The various provisions of this Agreement are severable and if any such provision or part thereof is held to be void, voidable, invalid, unlawful or unenforceable by any Court of competent jurisdiction such void, voidable, invalid, unlawful or unenforceable provision shall be deemed severed from this Agreement and shall not affect the remaining provisions of this Agreement or as the case may be, the remainder of the relevant provisions which shall remain in full force and effect and in substitution for any such provision held to be void, voidable, invalid, unlawful or unenforceable, there shall be substituted by mutual consultation and agreement of the Parties a provision of similar import reflecting the original intent of the Parties to the extent permissible under Applicable Laws.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">UPDATION OF THE INFORMATION BY THE COMPANY:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER acknowledges that the Company provides Services with reasonable diligence and care. It endeavours its best to ensure that USER does not face any inconvenience. However, sometimes, the information, Software, Products, and Services included in or available through the Company Platform or other sales channels and ad materials may include inaccuracies or typographical errors which will be immediately corrected as soon as the Company notices them. Changes are/may be periodically made/added to the information provided such. The Company may make improvements and/or changes in the Company Platform at any time without any notice to the USER. Any advice received except through an authorized representative of the Company via the Company Platform should not be relied upon for any decisions.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">NO WAIVER:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Save where this Agreement expressly provides, neither Party shall be deemed to have waived any right, power, privilege or remedy under this Agreement unless such Party shall have delivered to the other Party a written waiver signed by an authorised officer of such waiving Party. No failure or delay on the part of either Party in exercising any right, power, privilege or remedy hereunder shall operate as a waiver, default or acquiescence thereof, nor shall any waiver on the part of either Party of any right, power, privilege or remedy hereunder operate as a waiver of any other right, power, privilege or remedy, nor shall any single or partial exercise of any right, power, privilege or remedy hereunder preclude any other or further exercise thereof or the exercise of any other right, power, privilege or remedy hereunder.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">AMENDMENTS AND MODIFICATIONS:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company reserves the right to change the terms, conditions, and notices under which the Company’s Platform is offered, including but not limited to the charges. The USER is responsible for regularly reviewing these terms and conditions.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">JURISDICTION:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The Company hereby expressly disclaims any implied warranties imputed by the laws of any jurisdiction or country other than those where it is operating its offices. The Company considers itself and intends to be subject to the jurisdiction only of the courts of Delhi, India.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">GOVERNING LAWS AND ARBITRATION:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Any dispute, difference, controversy or claim (“Dispute”) arising between the Parties out of or in relation to or in connection with this Agreement, of the breach, termination, effect, validity, interpretation or application of this Agreement or as to their rights, duties or liabilities thereunder, or as to any act, matter or thing arising out of, consequent to or in connection with this Agreement, shall be settled by the Parties by mutual negotiations and agreement. If, for any reason, such Dispute cannot be resolved amicably by the Parties, the same shall then be referred to and settled by way of arbitration proceedings in accordance with the Arbitration and Conciliation Act, 1996 or any subsequent enactment or amendment thereto (the “Arbitration Act”). A sole Arbitrator shall be appointed by the Company. The decision of the Arbitrator shall be final and binding upon the Parties. The venue of arbitration proceedings shall be Delhi. The language of the arbitration and the award shall be English. This Agreement shall be construed in accordance with the laws of India.</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">MISCELLANEOUS:</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">This Agreement represent the entire Agreement between the Parties as to the subject matter hereof and supersede all prior understandings between the Parties on the subject-matter hereof.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">No amendments and/or modifications to this Agreement shall be valid unless executed in writing and signed by authorized persons of both the Parties.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Termination of this Agreement for any because whatsoever shall not release a Party from any liability which, at the time of termination, has already accrued to the other Party or which may thereafter accrue in respect of any act or omission prior to such termination.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Article headings are inserted for convenience of reference only and shall not be deemed to affect the interpretation of this Agreement or of any clause.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Each Party shall co-operate with the other and execute and deliver to the other such instruments and documents and take such other actions as may be reasonably requested from time to time in order to carry out, give effect to and confirm their rights and the intended purpose of this Agreement.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">No remedy conferred by any of the provisions of this Agreement is intended to be exclusive of any other remedy which is otherwise available at law, in equity, by statute or otherwise, or any other remedy given hereunder or now or hereafter existing at law, in equity, by statute, or otherwise, except as stated to the contrary in this Agreement. The election of any one or more of such remedies by any of the Parties hereto shall not constitute a waiver by such Party of the right to pursue any other available remedy.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The provisions of the following clauses of this Agreement shall survive the termination or expiry hereof.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">IN WITNESS WHEREOF the Parties hereto have hereunto executed these presents on the day and the date first hereinafter written.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">The USER hereby agrees to ensure to isolate and clearly identify all Customer information, documents (in hard copies or soft files), computerized data/information, records and assets to protect the confidentiality of the Customers information. BY CLICKING I ACCEPT, USER (INCLUDING PERSON ACTING ON BEHALF OF USER) CONFIRMS THAT THE USER OR ANY OTHER LEGAL ENTITY AS THE CASE MAY BE, HAS NECESSARY AUTHORITY TO ACCEPT THIS AGREEMENT ON ITS BEHALF.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Personal Details</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Personal Name</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">WAHAJUL HAQUE</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Business Name</p>
<h3 className="text-base font-extrabold text-slate-900 mt-6 border-b border-slate-200 pb-1">SHAHPARPAY SOLUTIONS PVT LTD</h3>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Business Add.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">4/1 Victoria Lane, Telinipara, Bhadreswar, Hooghly, West Bengal 712125, Burdwan Division, West Bengal</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Business Area.</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Bhadreswar</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">Hooghly</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">kindly sign here</p>
<p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-mono">I Accept</p>
                        </div>
                    </div>

                    {/* LEGAL HUB QUICK NAV GRID */}
                    <div className="bg-white rounded-[24px] border border-slate-200 p-6 shadow-sm">
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">Legal &amp; Compliance Network</h3>
                        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 text-xs font-bold text-slate-700">
                            <Link to="/about" className="p-3 rounded-xl bg-slate-50 hover:bg-[#f0fdf4] hover:text-[#008c46] border border-slate-200 text-center transition-colors">About Us</Link>
                            <Link to="/terms" className="p-3 rounded-xl bg-slate-50 hover:bg-[#f0fdf4] hover:text-[#008c46] border border-slate-200 text-center transition-colors">General Terms</Link>
                            <Link to="/retailer-terms" className="p-3 rounded-xl bg-[#008c46] text-white border border-[#008c46] text-center shadow-xs">Retailer Terms</Link>
                            <Link to="/aeps-terms" className="p-3 rounded-xl bg-slate-50 hover:bg-[#f0fdf4] hover:text-[#008c46] border border-slate-200 text-center transition-colors">AEPS Terms</Link>
                            <Link to="/aeps-permission" className="p-3 rounded-xl bg-slate-50 hover:bg-[#f0fdf4] hover:text-[#008c46] border border-slate-200 text-center transition-colors">AEPS Declaration</Link>
                            <Link to="/refund-policy" className="p-3 rounded-xl bg-slate-50 hover:bg-[#f0fdf4] hover:text-[#008c46] border border-slate-200 text-center transition-colors">Refund Policy</Link>
                        </div>
                    </div>
                </div>
            </section>

            <LandingFooter />
        </div>
    );
};

export default RetailerTerms;
